name: algal-bloom-paper
channels:
 - conda-forge
dependencies:
 - python ~=3.10

 ###################################################
 # Imported dependencies and extensions            #
 ###################################################

 - jupyterlab
 - matplotlib
 - cartopy
 - xarray
 - dask
 - h5netcdf
 - scipy
 - affine
 - pip:
   - /home/apbarret/src/nsidc_projections